package com.example.ispnexus.navigation

const val SUPER_ADMIN        = "super_admin"
const val LOG_IN             = "login"
const val REGISTER_COMPANY   = "register"
const val APPROVED_COMPANIES = "approved_companies"
const val SYSTEM_ANALYTICS   = "system_analytics"
const val ADMIN              = "admin"
const val ROLE_SELECTION     = "role_selection"
const val TECHNICIAN_DASHBOARD = "technician_dashboard"
const val FINANCE_DASHBOARD  = "finance_dashboard"
const val PLANS              = "plans"
const val INSTITUTIONS       = "institutions"
const val RECORD_PAYMENT     = "record_payment"
const val PAYMENTS           = "payments"
const val INVOICES           = "invoices"
const val REPORTS            = "reports"
const val MORE               = "more"
const val DEFAULTERS         = "defaulters"
const val GENERATE_INVOICE   = "generate_invoice"
const val EXPORT_REPORT      = "export_report"
const val SUBSCRIPTIONS      = "subscriptions"
const val STAFF              = "staff"
const val STAFF_REGISTER     = "staff_register"
const val STAFF_WAITING      = "staff_waiting"
const val STAFF_REJECTED     = "staff_rejected"